-- create target table
CREATE TABLE TARGET_TABLE_SCD3 (
    EMPLOYEE_KEY NUMBER PRIMARY KEY,
    EMPLOYEE_ID VARCHAR2(50),
    EMPLOYEE_NAME VARCHAR2(100),
    PREV_EMPLOYEE_NAME VARCHAR2(100),
    GENDER VARCHAR2(10),
    STATUS VARCHAR2(10),
    PREV_STATUS VARCHAR2(10),
    HIRE_DATE DATE
);

-- LOAD INITIAL DATA
INSERT INTO TARGET_TABLE_SCD3 VALUES (SEQ_EMP.NEXTVAL, 'E001', 'Sathish Kumar', NULL, 'MALE', 'ACTIVE', NULL, DATE '2023-06-01');
INSERT INTO TARGET_TABLE_SCD3 VALUES (SEQ_EMP.NEXTVAL, 'E002', 'Anita Sharma', NULL, 'FEMALE', 'ACTIVE', NULL, DATE '2022-03-15');
INSERT INTO TARGET_TABLE_SCD3 VALUES (SEQ_EMP.NEXTVAL, 'E003', 'Rahul Verma', NULL, 'MALE', 'INACTIVE', NULL, DATE '2021-11-20');
COMMIT;

-- CREATE SOURCE TABLE
CREATE SOURCE_TABLE_SCD3 (
    EMPLOYEE_ID VARCHAR2(50),
    EMPLOYEE_NAME VARCHAR2(100),
    GENDER VARCHAR2(10),
    STATUS VARCHAR2(10),
    HIRE_DATE DATE
);

-- LOAD THE CHANGED DATA TO SOURCE TABLE
INSERT INTO SOURCE_TABLE_SCD3 VALUES ('E001', 'Sathish Kumar Y', 'MALE', DATE '2023-06-01', 'ACTIVE');
INSERT INTO SOURCE_TABLE_SCD3 VALUES ('E002', 'Anita Sharma', 'FEMALE', DATE '2022-03-15', 'INACTIVE');
INSERT INTO SOURCE_TABLE_SCD3 VALUES ('E004', 'Priya Reddy', 'FEMALE', DATE '2024-01-10', 'ACTIVE');
COMMIT;

-- STEP 1 : UPDATE CHANGED RECORDS
UPDATE TARGET_TABLE_SCD3 T
SET
    -- SHIFT CURRENT VALUE TO PREVIOUS VALUE
    PREV_EMPLOYEE_NAME = T.EMPLOYEE_NAME,
    PREV_STATUS = T.STATUS,
    -- SET THE NEW CURRENT VALUES
    EMPLOYEE_NAME = (
            SELECT S.EMPLOYEE_NAME
            FROM SOURCE_TABLE_SCD3
            WHERE S.EMPLOYEE_ID = T.EMPLOYEE_ID
            ),
    STATUS = (
            SELECT S.STATUS
            FROM SOURCE_TABLE_SCD3 S
            WHERE S.EMPLOYEE_ID = T.EMPLOYEE_ID
        )
WHERE EXISTS (
                SELECT 1
                FROM SOURCE_TABLE_SCD3 S
                WHERE S.EMPLOYEE_ID = T.EMPLOYEE_ID
                AND (
                    NVL(T.EMPLOYEE_NAME, 'X') <> NVL(S.EMPLOYEE_NAME, 'X') OR
                    NVL(T.STATUS, 'X') <> NVL(S.STATUS, 'X')
                    )
);

-- STEP 2: INSERT NEW RECORDS INTO TARGET TABLE
INSERT INTO TARGET_TABLE_SCD3 (
    EMPLOYEE_KEY,
    EMPLOYEE_ID,
    EMPLOYEE_NAME,
    PREV_EMPLOYEE_NAME,
    GENDER,
    STATUS,
    PREV_STATUS,
    HIRE_DATE
    )
SELECT
    SEQ_EMP.NEXTVAL,
    S.EMPLOYEE_ID,
    S.EMPLOYEE_NAME,
    NULL,
    S.GENDER,
    S.STATUS,
    NULL,
    S.HIRE_DATE
FROM SOURCE_TABLE_SCD3 S
WHERE NOT EXISTS (
    SELECT 1
    FROM TARGET_TABLE_SCD3 T
    WHERE T.EMPLOYEE_ID = S.EMPLOYEE_ID
);

-- MERGE STATEMENT
MERGE INTO TARGET_TABLE_SCD3 T
USING SOURCE_TABLE_SCD3 S
ON (T.EMPLOYEE_ID = S.EMPLOYEE_ID)
WHEN MATCHED THEN
UPDATE SET
    -- SHIFTING CURRENT EMPLOYEE NAME TO PREVIOUS EMPLOYEE NAME IF CHANGED
    T.PREV_EMPLOYEE_NAME =
            CASE
                WHEN NVL(T.EMPLOYEE_NAME, 'X') <> NVL(S.EMPLOYEE_NAME, 'X')
                THEN T.EMPLOYEE_NAME
                ELSE T.PREV_EMPLOYEE_NAME
            END,
    T.PREV_STATUS =
            CASE
                WHEN NVL(T.STATUS, 'X') <> NVL(S.STATUS, 'X')
                THEN T.STATUS
                ELSE T.PREV_STATUS
            END,
    T.EMPLOYEE_NAME = S.EMPLOYEE_NAME,
    T.STATUS = S.STATUS,
    T.GENDER = S.GENDER,
    T.HIRE_DATE = S.HIRE_DATE
WHEN NOT MATCHED THEN
INSERT (
    EMPLOYEE_KEY,
    EMPLOYEE_ID,
    EMPLOYEE_NAME,
    PREV_EMPLOYEE_NAME,
    GENDER,
    STATUS,
    PREV_STATUS,
    HIRE_DATE
)
VALUES (
    SEQ_EMP.NEXTVAL,
    S.EMPLOYEE_ID,
    S.EMPLOYEE_NAME,
    NULL,
    S.GENDER,
    S.STATUS,
    NULL,
    S.HIRE_DATE
);
