-- Create Employee Dimension table
CREATE TABLE DIM_EMPLOYEE01(
    EMPLOYEE_KEY NUMBER PRIMARY KEY,
    EMPLOYEE_ID VARCHAR2(50),
    EMPLOYEE_NAME VARCHAR2(100),
    GENDER VARCHAR2(10),
    HIRE_DATE DATE,
    STATUS VARCHAR2(10)
);

-- CREATE Sequence table
CREATE SEQUENCE EMP_SEQ START WITH 1;

-- Insert data into Employee Dimension table
INSERT INTO DIM_EMPLOYEE01 VALUES (
    EMP_SEQ.NEXTVAL,
    'A1001',
    'James',
    'MALE',
    DATE '2023-06-01',
    'ACTIVE'
);
INSERT INTO DIM_EMPLOYEE01 VALUES (
    EMP_SEQ.NEXTVAL,
    'A1002',
    'Sachin Kumar',
    'MALE',
    DATE '2022-09-05',
    'INACTIVE'
);
INSERT INTO DIM_EMPLOYEE01 VALUES (
    EMP_SEQ.NEXTVAL,
    'A1003',
    'Smith Roy',
    'MALE',
    DATE '2023-11-04',
    'ACTIVE'
);
INSERT INTO DIM_EMPLOYEE01 VALUES (
    EMP_SEQ.NEXTVAL,
    'A1004',
    'Jones',
    'MALE',
    DATE '2021-03-23',
    'ACTIVE'
);
INSERT INTO DIM_EMPLOYEE01 VALUES (
    EMP_SEQ.NEXTVAL,
    'A1005',
    'Anitha Sharma',
    'FEMALE',
    DATE '2022-10-30',
    'ACTIVE'
);

-- IMPLEMENTING SCD TYPE 01 :

-- Create Stage Employee table
CREATE TABLE STG_EMPLOYEE01(
    EMPLOYEE_ID VARCHAR2(50),
    EMPLOYEE_NAME VARCHAR2(100),
    GENDER VARCHAR2(10),
    HIRE_DATE DATE,
    STATUS VARCHAR2(20)
);

-- INSERT DATA
INSERT INTO STG_EMPLOYEE01 VALUES (
    'A1001',
    'James',
    'MALE',
    DATE '2023-06-01',
    'INACTIVE'
);
INSERT INTO STG_EMPLOYEE01 VALUES (
    'A1003',
    'jONES Roy',
    'MALE',
    DATE '2023-11-04',
    'ACTIVE'
);
INSERT INTO STG_EMPLOYEE01 VALUES (
    'A1004',
    'MK jACKSON',
    'MALE',
    DATE '2021-03-23',
    'ACTIVE'
);
INSERT INTO STG_EMPLOYEE01 VALUES (
    'A1006',
    'Priya Reddy',
    'FEMALE',
    DATE '2024-02-18',
    'ACTIVE'
);

-- STEP 01 : Updating the MODIFIED data into the Target table
UPDATE DIM_EMPLOYEE01 D
SET (D.EMPLOYEE_ID,
     D.EMPLOYEE_NAME,
     D.GENDER,
     D.HIRE_DATE,
     D.STATUS) = (
                    SELECT
                        S.EMPLOYEE_ID,
                        S.EMPLOYEE_NAME,
                        S.GENDER,
                        S.HIRE_DATE,
                        S.STATUS
                    FROM STG_EMPLOYEE01 S
                    WHERE S.EMPLOYEE_ID = D.EMPLOYEE_ID

                )
WHERE EXISTS (
    SELECT 1
    FROM STG_EMPLOYEE01 S
    WHERE S.EMPLOYEE_ID = D.EMPLOYEE_ID
);

-- INSERING NEW records into target table
INSERT INTO DIM_EMPLOYEE01 (
    EMPLOYEE_KEY,
    EMPLOYEE_ID,
    EMPLOYEE_NAME,
    GENDER,
    HIRE_DATE,
    STATUS
    )
SELECT
    EMP_SEQ.NEXTVAL,
    S.EMPLOYEE_ID,
    S.EMPLOYEE_NAME,
    S.GENDER,
    S.HIRE_DATE,
    S.STATUS
FROM STG_EMPLOYEE01 S
WHERE NOT EXISTS (
    SELECT 1
    FROM DIM_EMPLOYEE01 D
    WHERE D.EMPLOYEE_ID = S.EMPLOYEE_ID
);

-- MERGE update and insert queries
    -- Note : ThIS Merge UPDATES All The Records, Including Changes and Unchanged : Non Optimized Implementation
MERGE INTO DIM_EMPLOYEE01 D
USING STG_EMPLOYEE01 S
ON (D.EMPLOYEE_ID = S.EMPLOYEE_ID)
WHEN MATCHED THEN
UPDATE SET
    D.EMPLOYEE_NAME = S.EMPLOYEE_NAME,
    D.GENDER = S.GENDER,
    D.HIRE_DATE = S.HIRE_DATE,
    D.STATUS = S.STATUS
WHEN NOT MATCHED THEN
INSERT (
    EMPLOYEE_KEY,
    EMPLOYEE_ID,
    EMPLOYEE_NAME,
    GENDER,
    HIRE_DATE,
    STATUS
)
VALUES (
    EMP_SEQ.NEXTVAL,
    S.EMPLOYEE_ID,
    S.EMPLOYEE_NAME,
    S.GENDER,
    S.HIRE_DATE,
    S.STATUS
);

-- MERGE (OPTIMIZED QUERY) - ONLY UPDATED AND NEW RECORDS WILL MERGE
    -- Note : ThIS Merge UPDATES Only The Records, Excluding Unchanged Records : Optimized Implementation
MERGE INTO DIM_EMPLOYEE01 D
USING STG_EMPLOYEE01 S
ON (D.EMPLOYEE_ID = S.EMPLOYEE_ID)
WHEN MATCHED THEN
UPDATE SET
    D.EMPLOYEE_NAME = S.EMPLOYEE_NAME,
    D.GENDER = S.GENDER,
    D.HIRE_DATE = S.HIRE_DATE,
    D.STATUS = S.STATUS
WHERE
    NVL(D.EMPLOYEE_NAME, 'X') <> NVL(S.EMPLOYEE_NAME, 'X') OR
    NVL(D.GENDER, 'X') <> NVL(S.GENDER, 'X') OR
    NVL(D.HIRE_DATE, DATE '1990-01-01') <> NVL(S.HIRE_DATE, DATE '1990-01-01') OR
    NVL(D.STATUS, 'X') <> NVL(S.STATUS, 'X')
WHEN NOT MATCHED THEN
INSERT (
    EMPLOYEE_KEY,
    EMPLOYEE_ID,
    EMPLOYEE_NAME,
    GENDER,
    HIRE_DATE,
    STATUS
)
VALUES (
    EMP_SEQ.NEXTVAL,
    S.EMPLOYEE_ID,
    S.EMPLOYEE_NAME,
    S.GENDER,
    S.HIRE_DATE,
    S.STATUS
);