-- CREATE TARGET TABLE
CREATE TABLE TARGET_TABLE_SCD1 (
    STUDENT_KEY NUMBER PRIMARY KEY,
    STUDENT_ID VARCHAR2(10),
    STUDENT_NAME VARCHAR2(30),
    AGE NUMBER(2),
    CLASS NUMBER (2),
    GRADE CHAR(1)
);

-- CREATE SEQUENCE
CREATE SEQUENCE STUDENT_SEQ START WITH 1;

-- LOAD INITIAL DATA
INSERT INTO TARGET_TABLE_SCD1 VALUES(STUDENT_SEQ.NEXTVAL, 'A101', 'John Doe', 13, 7, 'B');
INSERT INTO TARGET_TABLE_SCD1 VALUES(STUDENT_SEQ.NEXTVAL, 'A102', 'Smith Roy', 15, 9, 'C');
INSERT INTO TARGET_TABLE_SCD1 VALUES(STUDENT_SEQ.NEXTVAL, 'A103', 'Akhila Reddy', 9, 3, 'A');
INSERT INTO TARGET_TABLE_SCD1 VALUES(STUDENT_SEQ.NEXTVAL, 'A104', 'Chandrakanth', 14, 8, 'D');
commit;

-- CREATE SOURCE TABLE
CREATE TABLE SOURCE_TABLE_SCD1 (
    STUDENT_ID VARCHAR2(10),
    STUDENT_NAME VARCHAR2(30),
    AGE NUMBER(2),
    CLASS NUMBER (2),
    GRADE CHAR(1)
);

-- LOAD THE CHANGED DATA TO SOURCE TABLE
INSERT INTO SOURCE_TABLE_SCD1 VALUES('A101', 'John Doe', 13, 7, 'B');
INSERT INTO SOURCE_TABLE_SCD1 VALUES('A103', 'Akanksha', 10, 3, 'A');
INSERT INTO SOURCE_TABLE_SCD1 VALUES('A104', 'Chandrakanth', 15, 10, 'B');
INSERT INTO SOURCE_TABLE_SCD1 VALUES('A106', 'Jockey', 7, 2, 'C');
commit;

-- IMPLEMENTING SCD 1

-- STEP 1 : UPDATE CHANGED RECORDS
UPDATE TARGET_TABLE_SCD1 T
SET (T.STUDENT_ID,
     T.STUDENT_NAME,
     T.AGE,
     T.CLASS,
     T.GRADE ) = (
                    SELECT
                        S.STUDENT_ID,
                        S.STUDENT_NAME,
                        S.AGE,
                        S.CLASS,
                        S.GRADE
                    FROM SOURCE_TABLE_SCD1 S
                    WHERE S.STUDENT_ID = T.STUDENT_ID
                )
WHERE EXISTS (
    SELECT 1
    FROM SOURCE_TABLE_SCD1 S
    WHERE S.STUDENT_ID = T.STUDENT_ID
);

-- STEP 2: INSERT NEW RECORDS INTO TARGET TABLE
INSERT INTO TARGET_TABLE_SCD1 (
    STUDENT_KEY,
    STUDENT_ID,
    STUDENT_NAME,
    AGE,
    CLASS,
    GRADE
)
SELECT
    STUDENT_SEQ.NEXTVAL,
    S.STUDENT_ID,
    S.STUDENT_NAME,
    S.AGE,
    S.CLASS,
    S.GRADE
    FROM SOURCE_TABLE_SCD1 S
WHERE NOT EXISTS (
    SELECT 1
    FROM TARGET_TABLE_SCD1 T
    WHERE T.STUDENT_ID = S.STUDENT_ID
);

-- STEP 3 : MERGE UPDATE AND INSERT QUERIES
MERGE INTO TARGET_TABLE_SCD1 T
USING SOURCE_TABLE_SCD1 S
ON (T.STUDENT_ID = S.STUDENT_ID)
WHEN MATCHED THEN
UPDATE SET
    T.STUDENT_NAME = S.STUDENT_NAME,
    T.AGE = S.AGE,
    T.CLASS = S.CLASS,
    T.GRADE = S.GRADE
WHERE
    NVL(T.STUDENT_NAME, 'X') <> NVL(S.STUDENT_NAME, 'X') OR
    NVL(T.AGE, -1) <> NVL(S.AGE, -1) OR
    NVL(T.CLASS, -1) <> NVL(S.CLASS, -1) OR
    NVL(T.GRADE, 'X') <> NVL(S.GRADE, 'X')
WHEN NOT MATCHED THEN
INSERT (
    STUDENT_KEY,
    STUDENT_ID,
    STUDENT_NAME,
    AGE,
    CLASS,
    GRADE
)
VALUES (
    STUDENT_SEQ.NEXTVAL,
    S.STUDENT_ID,
    S.STUDENT_NAME,
    S.AGE,
    S.CLASS,
    S.GRADE
);