-- CREATE TARGET TABLE
CREATE TABLE TARGET_TABLE_SCD2 (
    STUDENT_KEY NUMBER PRIMARY KEY,
    STUDENT_ID VARCHAR2(10),
    STUDENT_NAME VARCHAR2(30),
    AGE NUMBER(2),
    CLASS NUMBER (2),
    GRADE CHAR(1),
    HIRE_DATE DATE,
    START_DATE DATE,
    END_DATE DATE,
    IS_ACTIVE CHAR(1)
);

-- LOAD INITIAL DATA
INSERT INTO TARGET_TABLE_SCD2 VALUES(STUDENT_SEQ.NEXTVAL, 'A101', 'John Doe', 13, 7, 'B', DATE '2023-06-01', DATE '2023-06-01', DATE '9999-12-31', 'Y');
INSERT INTO TARGET_TABLE_SCD2 VALUES(STUDENT_SEQ.NEXTVAL, 'A102', 'Smith Roy', 15, 9, 'C', DATE '2022-03-15', DATE '2022-03-15', DATE '9999-12-31', 'Y');
INSERT INTO TARGET_TABLE_SCD2 VALUES(STUDENT_SEQ.NEXTVAL, 'A103', 'Akhila Reddy', 9, 3, 'A', DATE '2021-11-20', DATE '2021-11-20', DATE '9999-12-31', 'Y');
INSERT INTO TARGET_TABLE_SCD2 VALUES(STUDENT_SEQ.NEXTVAL, 'A104', 'Chandrakanth', 14, 8, 'D', DATE '2024-01-10',  DATE '2024-01-10', DATE '9999-12-31', 'Y');
commit;


-- CREATE SOURCE TABLE
CREATE TABLE SOURCE_TABLE_SCD2 (
    STUDENT_ID VARCHAR2(10),
    STUDENT_NAME VARCHAR2(30),
    AGE NUMBER(2),
    CLASS NUMBER (2),
    GRADE CHAR(1),
    HIRE_DATE DATE
);

-- LOAD THE CHANGED DATA TO SOURCE TABLE
INSERT INTO SOURCE_TABLE_SCD2 VALUES('A101', 'John Doe', 13, 7, 'B', DATE '2023-06-01');
INSERT INTO SOURCE_TABLE_SCD2 VALUES('A103', 'Akanksha', 10, 3, 'A', DATE '2022-03-15');
INSERT INTO SOURCE_TABLE_SCD2 VALUES('A104', 'Chandrakanth', 15, 10, 'B', DATE '2021-11-20');
INSERT INTO SOURCE_TABLE_SCD2 VALUES('A106', 'Jockey', 7, 2, 'C', DATE '2024-01-10');
INSERT INTO SOURCE_TABLE_SCD2 VALUES('A102', 'Smith Roy', 15, 9, 'A', DATE '2022-03-15');

commit;

-- IMPLEMENTING SCD 2

-- STEP 1: IDENTIFY THE SCTIVE CHANGED RECORDS
SELECT T.*, S.*
FROM TARGET_TABLE_SCD2 T
JOIN SOURCE_TABLE_SCD2 S
ON (T.STUDENT_ID = S.STUDENT_ID)
WHERE T.IS_ACTIVE = 'Y'
AND (
    NVL(T.STUDENT_NAME, 'X') <> NVL(S.STUDENT_NAME, 'X') OR
    NVL(T.AGE, -1) <> NVL(S.AGE, -1) OR
    NVL(T.CLASS, -1) <> NVL(S.CLASS, -1) OR
    NVL(T.GRADE, 'X') <> NVL(S.GRADE, 'X')
);

-- STEP 2: UPDATE THE END_DATE AND IS_ACTIVE TO THE CHANGED RECORDS
UPDATE TARGET_TABLE_SCD2 T
SET
    END_DATE = SYSDATE - 1,
    IS_ACTIVE = 'N'
WHERE T.IS_ACTIVE = 'Y'
AND EXISTS (
    SELECT 1
    FROM SOURCE_TABLE_SCD2 S
    WHERE S.STUDENT_ID = T.STUDENT_ID
    AND (
        NVL(T.STUDENT_NAME, 'X') <> NVL(S.STUDENT_NAME, 'X') OR
        NVL(T.AGE, -1) <> NVL(S.AGE, -1) OR
        NVL(T.CLASS, -1) <> NVL(S.CLASS, -1) OR
        NVL(T.GRADE, 'X') <> NVL(S.GRADE, 'X')
    )
);

-- STEP 3: INSERT CHANGED RECORDS AS NEW RECORDS IN TARGET TABLE
INSERT INTO TARGET_TABLE_SCD2 (
    STUDENT_KEY,
    STUDENT_ID,
    STUDENT_NAME,
    AGE,
    CLASS,
    GRADE,
    HIRE_DATE,
    START_DATE,
    END_DATE,
    IS_ACTIVE
)
SELECT
    STUDENT_SEQ.NEXTVAL,
    S.STUDENT_ID,
    S.STUDENT_NAME,
    S.AGE,
    S.CLASS,
    S.GRADE,
    S.HIRE_DATE,
    SYSDATE,
    DATE '9999-12-31',
    'Y'
FROM SOURCE_TABLE_SCD2 S
JOIN TARGET_TABLE_SCD2 T
ON (S.STUDENT_ID = T.STUDENT_ID)
WHERE T.IS_ACTIVE = 'N'
AND TRUNC(T.END_DATE) = TRUNC(SYSDATE) - 1;

-- STEP 4 : INSERT NEW RECORDS INTO TARGET TABLE
INSERT INTO TARGET_TABLE_SCD2 (
    STUDENT_KEY,
    STUDENT_ID,
    STUDENT_NAME,
    AGE,
    CLASS,
    GRADE,
    HIRE_DATE,
    START_DATE,
    END_DATE,
    IS_ACTIVE
)
SELECT
    STUDENT_SEQ.NEXTVAL,
    S.STUDENT_ID,
    S.STUDENT_NAME,
    S.AGE,
    S.CLASS,
    S.GRADE,
    S.HIRE_DATE,
    SYSDATE,
    DATE '9999-12-31',
    'Y'
FROM SOURCE_TABLE_SCD2 S
WHERE NOT EXISTS (
    SELECT 1
    FROM TARGET_TABLE_SCD2 T
    WHERE T.STUDENT_ID = S.STUDENT_ID
);

Implementing SCD Type 2 Using MERGE Statement
--------------------------------------------------------------

Step 01 : Handling Expire Old Records For Changed data in The Source
---------
MERGE INTO TARGET_TABLE_SCD2 T
USING SOURCE_TABLE_SCD2 S
ON (T.STUDENT_ID = S.STUDENT_ID)
WHEN MATCHED THEN
UPDATE SET
	T.END_DATE = SYSDATE - 1,
	T.IS_ACTIVE = 'N'
WHERE
    T.IS_ACTIVE = 'Y'
    AND (
        NVL(T.STUDENT_NAME,'X') <> NVL(S.STUDENT_NAME,'X') OR
        NVL(T.CLASS, -1) <> NVL(S.CLASS, -1) OR
        NVL(T.AGE, -1) <> NVL(S.AGE, -1) OR
        NVL(T.GRADE,'X') <> NVL(S.GRADE,'X')
    );

Step 02 : Handling Expire New Records For New Version of Records Inserted into The Source
---------

MERGE INTO TARGET_TABLE_SCD2 T
USING (
	SELECT S.*
	FROM SOURCE_TABLE_SCD2 S
	) S
ON	(
	T.STUDENT_ID = S.STUDENT_ID AND
	T.IS_ACTIVE = 'Y'
	)
WHEN NOT MATCHED THEN
INSERT (
	STUDENT_KEY,
	STUDENT_ID,
	STUDENT_NAME,
	AGE,
    CLASS,
    GRADE,
	HIRE_DATE,
	START_DATE,
	END_DATE,
	IS_ACTIVE
	)
VALUES (
	STUDENT_SEQ.NEXTVAL,
	S.STUDENT_ID,
	S.STUDENT_NAME,
	S.AGE,
    S.CLASS,
    S.GRADE,
	S.HIRE_DATE,
	SYSDATE,
	DATE '9999-12-31',
	'Y'
);
