-- CREATE TARGET TABLE
CREATE TABLE TARGET_TABLE_SCD3 (
    STUDENT_KEY NUMBER PRIMARY KEY,
    STUDENT_ID VARCHAR2(10),
    STUDENT_NAME VARCHAR2(30),
    PREV_STUDENT_NAME VARCHAR2(30),
    AGE NUMBER(2),
    CLASS NUMBER (2),
    PREV_CLASS NUMBER(2),
    GRADE CHAR(1),
    PREV_GRADE CHAR(1)
);

-- LOAD INITIAL DATA
INSERT INTO TARGET_TABLE_SCD3 VALUES(STUDENT_SEQ.NEXTVAL, 'A101', 'John Doe', NULL, 13, 7, NULL, 'B', NULL);
INSERT INTO TARGET_TABLE_SCD3 VALUES(STUDENT_SEQ.NEXTVAL, 'A102', 'Smith Roy', NULL, 15, 9, NULL, 'C', NULL);
INSERT INTO TARGET_TABLE_SCD3 VALUES(STUDENT_SEQ.NEXTVAL, 'A103', 'Akhila Reddy', NULL, 9, 3, NULL, 'A', NULL);
INSERT INTO TARGET_TABLE_SCD3 VALUES(STUDENT_SEQ.NEXTVAL, 'A104', 'Chandrakanth', NULL, 14, 8, NULL, 'D', NULL);
commit;

-- CREATE SOURCE TABLE
CREATE TABLE SOURCE_TABLE_SCD3 (
    STUDENT_ID VARCHAR2(10),
    STUDENT_NAME VARCHAR2(30),
    AGE NUMBER(2),
    CLASS NUMBER (2),
    GRADE CHAR(1)
);

-- LOAD THE CHANGED DATA TO SOURCE TABLE
INSERT INTO SOURCE_TABLE_SCD3 VALUES('A101', 'John Doe', 13, 7, 'B');
INSERT INTO SOURCE_TABLE_SCD3 VALUES('A103', 'Akanksha', 10, 3, 'A');
INSERT INTO SOURCE_TABLE_SCD3 VALUES('A104', 'Chandrakanth', 15, 10, 'B');
INSERT INTO SOURCE_TABLE_SCD3 VALUES('A106', 'Jockey', 7, 2, 'C');
commit;

-- IMPLEMENTING SCD 3

-- STEP 1: UPDATE CHANGED RECORDS
UPDATE TARGET_TABLE_SCD3 T
SET
    -- SHIFT CURRENT VALUES TO PREVIOUS VALUES
    PREV_STUDENT_NAME = T.STUDENT_NAME,
    PREV_CLASS = T.CLASS,
    PREV_GRADE = T.GRADE,
    -- SET THE NEW CURRENT VALUES
    STUDENT_NAME = (
        SELECT S.STUDENT_NAME
        FROM SOURCE_TABLE_SCD3 S
        WHERE S.STUDENT_ID = T.STUDENT_ID
    ),
    CLASS = (
        SELECT S.CLASS
        FROM SOURCE_TABLE_SCD3 S
        WHERE S.STUDENT_ID = T.STUDENT_ID
    ),
    GRADE = (
        SELECT S.GRADE
        FROM SOURCE_TABLE_SCD3 S
        WHERE S.STUDENT_ID = T.STUDENT_ID
    )
WHERE EXISTS (
    SELECT 1
    FROM SOURCE_TABLE_SCD3 S
    WHERE S.STUDENT_ID = T.STUDENT_ID
    AND (
        NVL(T.STUDENT_NAME, 'X') <> NVL(S.STUDENT_NAME, 'X') OR
        NVL(T.CLASS, -1) <> NVL(S.CLASS, -1) OR
        NVL(T.GRADE, 'X') <> NVL(S.GRADE, 'X')
    )
);

-- STEP 2: INSERT NEW RECORD
INSERT INTO TARGET_TABLE_SCD3 (
    STUDENT_KEY,
    STUDENT_ID,
    STUDENT_NAME,
    PREV_STUDENT_NAME,
    AGE,
    CLASS,
    PREV_CLASS,
    GRADE,
    PREV_GRADE
)
SELECT
    STUDENT_SEQ.NEXTVAL,
    S.STUDENT_ID,
    S.STUDENT_NAME,
    NULL,
    S.AGE,
    S.CLASS,
    NULL,
    S.GRADE,
    NULL
FROM SOURCE_TABLE_SCD3 S
WHERE NOT EXISTS (
    SELECT 1
    FROM TARGET_TABLE_SCD3 T
    WHERE T.STUDENT_ID = S.STUDENT_ID
);

-- MERGE QUERY
MERGE INTO TARGET_TABLE_SCD3 T
USING SOURCE_TABLE_SCD3 S
ON (T.STUDENT_ID = S.STUDENT_ID)
WHEN MATCHED THEN
UPDATE SET
    T.PREV_STUDENT_NAME =
            CASE
                WHEN NVL(T.STUDENT_NAME, 'X') <> NVL(S.STUDENT_NAME, 'X')
                THEN T.STUDENT_NAME
                ELSE T.PREV_STUDENT_NAME
            END,
    T.PREV_CLASS =
            CASE
                WHEN NVL(T.CLASS, -1) <> NVL(S.CLASS, -1)
                THEN T.CLASS
                ELSE T.PREV_CLASS
            END,
    T.PREV_GRADE =
            CASE
                WHEN NVL(T.GRADE, 'X') <> NVL(S.GRADE, 'X')
                THEN T.GRADE
                ELSE T.PREV_GRADE
            END,
    T.STUDENT_NAME = S.STUDENT_NAME,
    T.CLASS = S.CLASS,
    T.GRADE = S.GRADE,
    T.AGE = S.AGE
WHEN NOT MATCHED THEN
INSERT (
    STUDENT_KEY,
    STUDENT_ID,
    STUDENT_NAME,
    PREV_STUDENT_NAME,
    AGE,
    CLASS,
    PREV_CLASS,
    GRADE,
    PREV_GRADE
)
VALUES (
    STUDENT_SEQ.NEXTVAL,
    S.STUDENT_ID,
    S.STUDENT_NAME,
    NULL,
    S.AGE,
    S.CLASS,
    NULL,
    S.GRADE,
    NULL
);