-- TARGET TABLE
CREATE TABLE TARGET_EMPLOYEE(
    EMPLOYEE_KEY NUMBER PRIMARY KEY,
    EMPLOYEE_ID VARCHAR2(50),
    EMPLOYEE_NAME VARCHAR2(100),
    GENDER VARCHAR2(10),
    HIRE_DATE DATE,
    STATUS VARCHAR2(10)
);

-- Insert data into TARGET table
INSERT INTO TARGET_EMPLOYEE VALUES (SEQ_EMP.NEXTVAL, 'E001', 'Sathish Kumar', 'MALE', DATE '2023-06-01', 'ACTIVE');
INSERT INTO TARGET_EMPLOYEE VALUES (SEQ_EMP.NEXTVAL, 'E002', 'Anita Sharma', 'FEMALE', DATE '2022-03-15', 'ACTIVE');
INSERT INTO TARGET_EMPLOYEE VALUES (SEQ_EMP.NEXTVAL, 'E003', 'Rahul Verma', 'MALE', DATE '2021-11-20', 'INACTIVE');
INSERT INTO TARGET_EMPLOYEE VALUES (SEQ_EMP.NEXTVAL, 'E004', 'Priya Reddy', 'FEMALE', DATE '2024-01-10', 'ACTIVE');
INSERT INTO TARGET_EMPLOYEE VALUES (SEQ_EMP.NEXTVAL, 'E005', 'Arjun Singh', 'MALE', DATE '2020-08-05', 'ACTIVE');
COMMIT;


-- SOURCE TABLE
CREATE TABLE SOURCE_EMPLOYEE(
    EMPLOYEE_ID VARCHAR2(50),
    EMPLOYEE_NAME VARCHAR2(100),
    GENDER VARCHAR2(10),
    HIRE_DATE DATE,
    STATUS VARCHAR2(20)
);

-- INSERT DATA INTO SOURCE TABLE
INSERT INTO SOURCE_EMPLOYEE VALUES ('E007', 'Preetham Jha', 'MALE', DATE '2024-07-03', 'ACTIVE');
INSERT INTO SOURCE_EMPLOYEE VALUES ('E002', 'Anita Sharma', 'FEMALE', DATE '2022-03-15', 'ACTIVE');
INSERT INTO SOURCE_EMPLOYEE VALUES ('E006', 'Neha Gupta S', 'FEMALE', DATE '2024-05-01', 'ACTIVE');
COMMIT;

-- STEP 01 : MODIFY THE EXISTING TARGET TABLE : ADD REQUIRED COLUMNS
ALTER TABLE TARGET_EMPLOYEE
ADD (
    START_DATE DATE,
    END_DATE DATE,
    IS_ACTIVE CHAR(1)
);

-- STEP 02 : UPDATE THE EXISTING DATA
UPDATE TARGET_EMPLOYEE
SET
    START_DATE = HIRE_DATE,
    END_DATE = DATE '9999-12-31',
    IS_ACTIVE = 'Y'
;

-- STEP 03 : IDENTIFY THE CHANGED ACTIVE RECORDS
SELECT T.*, S.*
FROM TARGET_EMPLOYEE T
JOIN SOURCE_EMPLOYEE S
ON (T.EMPLOYEE_ID = S.EMPLOYEE_ID)
WHERE T.IS_ACTIVE = 'Y'
AND (
    NVL(T.EMPLOYEE_NAME, 'X') <> NVL(S.EMPLOYEE_NAME, 'X') OR
    NVL(T.GENDER, 'X') <> NVL(S.GENDER, 'X') OR
    NVL(T.STATUS, 'X') <> NVL(S.STATUS, 'X')
);

-- STEP 04 : SET THE END DATE TO THE CHANGED RECORDS
UPDATE TARGET_EMPLOYEE T
SET
    T.END_DATE = SYSDATE - 1,
    T.IS_ACTIVE = 'N'
WHERE T.IS_ACTIVE = 'Y'
AND EXISTS (
    SELECT 1
    FROM SOURCE_EMPLOYEE S
    WHERE S.EMPLOYEE_ID = T.EMPLOYEE_ID
    AND (
        NVL(T.EMPLOYEE_NAME, 'X') <> NVL(S.EMPLOYEE_NAME, 'X') OR
        NVL(T.GENDER, 'X') <> NVL(S.GENDER, 'X') OR
        NVL(T.STATUS, 'X') <> NVL(S.STATUS, 'X')
    )
);

-- STEP 05 : INSERT CHANGED RECORDS AS NEW RECORD IN TARGET TABLE
INSERT INTO TARGET_EMPLOYEE (
    EMPLOYEE_KEY,
    EMPLOYEE_ID,
    EMPLOYEE_NAME,
    GENDER,
    HIRE_DATE,
    STATUS,
    START_DATE,
    END_DATE,
    IS_ACTIVE
)
SELECT
    SEQ_EMP.NEXTVAL,
    S.EMPLOYEE_ID,
    S.EMPLOYEE_NAME,
    S.GENDER,
    S.HIRE_DATE,
    S.STATUS,
    SYSDATE,
    DATE '9999-12-31',
    'Y'
FROM SOURCE_EMPLOYEE S
JOIN TARGET_EMPLOYEE T
ON S.EMPLOYEE_ID = T.EMPLOYEE_ID
WHERE T.IS_ACTIVE = 'N'
AND TRUNC(T.END_DATE) = TRUNC(SYSDATE) - 1
;

-- STEP 06 : INSERT NEW RECORDS FROM SOURCE TO TARGET TABLE
INSERT INTO TARGET_EMPLOYEE (
    EMPLOYEE_KEY,
    EMPLOYEE_ID,
    EMPLOYEE_NAME,
    GENDER,
    HIRE_DATE,
    STATUS,
    START_DATE,
    END_DATE,
    IS_ACTIVE
)
SELECT
    SEQ_EMP.NEXTVAL,
    S.EMPLOYEE_ID,
    S.EMPLOYEE_NAME,
    S.GENDER,
    S.HIRE_DATE,
    S.STATUS,
    SYSDATE,
    DATE '9999-12-31',
    'Y'
FROM SOURCE_EMPLOYEE S
WHERE NOT EXISTS (
    SELECT 1
    FROM TARGET_EMPLOYEE T
    WHERE T.EMPLOYEE_ID = S.EMPLOYEE_ID
);

Implementing SCD Type 2 Using MERGE Statement
--------------------------------------------------------------
1. A Single MERGE Cannot Both UPDATE (Expire Old Record) and INSERT (New Version) in One Single Pass
2. We Have To Use Two MERGE Statements
	1. MERGE 1 For Expire Old Records : UPDATE
	2. MERGE 2 For Inserting New Records : INSERT

Step 01 : Handling Expire Old Records For Changed data in The Source
---------
MERGE INTO TARGET_EMPLOYEE T
USING SOURCE_EMPLOYEE S
ON (T.EMPLOYEE_ID = S.EMPLOYEE_ID AND T.IS_ACTIVE = 'Y')
WHEN MATCHED THEN
UPDATE SET
	T.END_DATE = SYSDATE - 1,
	T.IS_ACTIVE = 'N'
WHERE
	NVL(T.EMPLOYEE_NAME,'X') <> NVL(S.EMPLOYEE_NAME,'X') OR
	NVL(T.GENDER,'X') <> NVL(S.GENDER,'X') OR
	NVL(T.STATUS,'X') <> NVL(S.STATUS,'X');

Step 02 : Handling Expire New Records For New Version of Records Inserted into The Source
---------

MERGE INTO TARGET_EMPLOYEE T
USING (
	SELECT S.*
	FROM SOURCE_EMPLOYEE S
	) S
ON	(
	T.EMPLOYEE_ID = S.EMPLOYEE_ID AND
	T.IS_ACTIVE = 'Y'
	)
WHEN NOT MATCHED THEN
INSERT (
	EMPLOYEE_KEY,
	EMPLOYEE_ID,
	EMPLOYEE_NAME,
	GENDER,
	HIRE_DATE,
	STATUS,
	START_DATE,
	END_DATE,
	IS_ACTIVE
	)
VALUES (
	SEQ_EMP.NEXTVAL,
	S.EMPLOYEE_ID,
	S.EMPLOYEE_NAME,
	S.GENDER,
	S.HIRE_DATE,
	S.STATUS,
	SYSDATE,
	DATE '9999-12-31',
	'Y'
);
